<?php


/**
 * This class defines the structure of the 'album_has_image' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/06/15 17:37:08
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AlbumHasImageTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AlbumHasImageTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('album_has_image');
		$this->setPhpName('AlbumHasImage');
		$this->setClassname('AlbumHasImage');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(false);
		// columns
		$this->addForeignPrimaryKey('ALBUM_ID', 'AlbumId', 'INTEGER' , 'album', 'ID', true, 10, null);
		$this->addForeignPrimaryKey('IMAGE_ID', 'ImageId', 'INTEGER' , 'image', 'ID', true, 10, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Album', 'Album', RelationMap::MANY_TO_ONE, array('album_id' => 'id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Image', 'Image', RelationMap::MANY_TO_ONE, array('image_id' => 'id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // AlbumHasImageTableMap
