<?php


/**
 * This class defines the structure of the 'anketa' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/06/15 17:37:08
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AnketaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AnketaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('anketa');
		$this->setPhpName('Anketa');
		$this->setClassname('Anketa');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 10, null);
		$this->addColumn('FIO', 'Fio', 'VARCHAR', true, 45, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', true, 45, null);
		$this->addColumn('PHONE', 'Phone', 'VARCHAR', true, 45, null);
		$this->addColumn('MESSAGE', 'Message', 'LONGVARCHAR', true, null, null);
		$this->addColumn('BIRTHDAY', 'Birthday', 'VARCHAR', true, 45, null);
		$this->addColumn('SEX', 'Sex', 'VARCHAR', true, 45, null);
		$this->addColumn('FAMILY', 'Family', 'VARCHAR', true, 45, null);
		$this->addForeignKey('IMAGE_ID', 'ImageId', 'INTEGER', 'image', 'ID', false, 10, null);
		$this->addColumn('ADRESS', 'Adress', 'LONGVARCHAR', true, null, null);
		$this->addColumn('EDU', 'Edu', 'VARCHAR', true, 45, null);
		$this->addColumn('WORK', 'Work', 'LONGVARCHAR', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Image', 'Image', RelationMap::MANY_TO_ONE, array('image_id' => 'id', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // AnketaTableMap
