<?php


/**
 * This class defines the structure of the 'image' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 06/07/15 23:37:47
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ImageTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ImageTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('image');
		$this->setPhpName('Image');
		$this->setClassname('Image');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 10, null);
		$this->addColumn('HASH', 'Hash', 'VARCHAR', false, 255, null);
		$this->addColumn('TITLE', 'Title', 'VARCHAR', false, 255, null);
		$this->addColumn('CONTENT', 'Content', 'CLOB', true, null, null);
		$this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
		$this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Album', 'Album', RelationMap::ONE_TO_MANY, array('id' => 'cover_image', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('AlbumHasImage', 'AlbumHasImage', RelationMap::ONE_TO_MANY, array('id' => 'image_id', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Anketa', 'Anketa', RelationMap::ONE_TO_MANY, array('id' => 'image_id', ), 'RESTRICT', 'CASCADE');
    $this->addRelation('News', 'News', RelationMap::ONE_TO_MANY, array('id' => 'image_id', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
		);
	} // getBehaviors()

} // ImageTableMap
