# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }
  
image-original:
  url:   /uploads/:hash
  param: { module: image, action: show }
  requirements:
    hash: ^([\w\d\.]*)$

image-resize:
  url:   /uploads/:x/:y/:hash
  param: { module: image, action: resize }
  requirements:
    hash: ^([\w\d\.]*)$

video-show:
  url:   /video/show/:id
  param: { module: videp, action: show }

video-index:
  url:   /video/:page
  param: { module: videp, action: show }

fotoalbum-show:
  url:   /fotoalbum/show/:id
  param: { module: fotoalbum, action: show }

fotoalbum-index:
  url:   /fotoalbum/:page
  param: { module: fotoalbum, action: index }

news-show:
  url:   /news/show/:id
  param: { module: news, action: show }

news-index:
  url:   /news/:page
  param: { module: news, action: index}

about:
  url:   /about
  param: { module: default, action: about }

anketa:
  url:   /anketa
  param: { module: anketa, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
