# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

confirmSuccess:
  metas:
    title: САУ Кировоград - Благодарим Вас за успешно поданую заявку на вступление
    description:  Официальный сайт Союза армян Украины в Кировоградской области - успешная заявка
    keywords:     Союз, армяне, Кировоград, община, землячество, сау, союз армян украины, армяне украины, спілка вірмен україни, вірмени україни, о нас, структура организации, структура, руководство
all:    
  metas:
    title:        САУ Кировоград - вступление в организацию
    description:  Официальный сайт Союза армян Украины в Кировоградской области, анкета для вступления в организацию
    keywords:     Союз, армяне, Кировоград, община, землячество, сау, союз армян украины, армяне украины, спілка вірмен україни, вірмени україни, членсво, членство, вступить, dcnegbnm, fhvzyt, erhfbyf
   
