<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/06 16:03:59
sfConfig::add(array(
  'app_ckfinder_active' => true,
  'app_ckfinder_basePath' => '/bend/js/ckfinder/',
  'app_ckeditor_basePath' => '/bend/js/ckeditor/',
));
