<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/17 14:13:55

return array(
'propel' => new sfPropelDatabase(array (
  'dsn' => 'mysql:dbname=armenian;host=localhost',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'name' => 'propel',
)),);
