<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/06/17 14:13:54
sfConfig::add(array(
  'app_ckfinder_active' => true,
  'app_ckfinder_basePath' => '/bend/js/ckfinder/',
  'app_ckeditor_basePath' => '/bend/js/ckeditor/',
));
