<?php

/**
 * Skeleton subclass for performing query and update operations on the 'album' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/07/15 12:45:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AlbumPeer extends BaseAlbumPeer {
    /**
     * get an array of images id using by all albums
     * @return array list of image_id of all Albums
     */
    static function getAllAlbumCoverImage() {
        $stm = Propel::getConnection()->prepare
                ('
                    SELECT
                        alb.cover_image
                    FROM
                        album alb
                ');
        $stm->execute();
        $albumCoverImage = $stm->fetchAll(PDO::FETCH_COLUMN, 0);
        return $albumCoverImage;
    }
    /**
     * 
     * @return array a list of main page images for slider (hash)
     */
    static function getMainPageImages(){
        $stm = Propel::getConnection()->prepare('
            SELECT
                image.hash
            FROM
                album_has_image
            INNER JOIN image ON image.id = album_has_image.image_id
            WHERE
                album_has_image.album_id = 1
        ');
        
        $stm->execute();
        $list = $stm->fetchAll(PDO::FETCH_COLUMN);
        return $list;
    }
    
}

// AlbumPeer
