<?php

/**
 * Skeleton subclass for performing query and update operations on the 'anketa' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/07/15 12:45:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AnketaPeer extends BaseAnketaPeer {

    /**
     * get an array of images id saved by anketas
     * @return array list of image_id of all anketas
     */
    static function getAllAnketaImageId() {
        $stm = Propel::getConnection()->prepare
                ('
                    SELECT
                        ank.image_id
                    FROM
                        anketa ank 
                ');
        $stm->execute();
        $anketaImageId = $stm->fetchAll(PDO::FETCH_COLUMN, 0);
        return $anketaImageId;
    }

}

// AnketaPeer
