<?php

/**
 * Skeleton subclass for performing query and update operations on the 'video' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/07/15 12:45:25
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VideoPeer extends BaseVideoPeer {

    /**
     * using for looking previos and next news at show news page
     * @return array list of newsid sorted by createdAt field
     */
    static function getVideosIdSortedByCreatedAt() {
        $stm                     = Propel::getConnection()->prepare
                ('
                    SELECT 
                        v.id
                      FROM
                        video v 
                      ORDER BY v.created_at DESC
                ');
        $stm->execute();
        $videoIdSortedByCreatedAt = $stm->fetchAll(PDO::FETCH_COLUMN, 0);
        return $videoIdSortedByCreatedAt;
    }

}

// VideoPeer
