generator:
  class: sfPropelGenerator
  param:
    model_class:           Video
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Video
    plural:                Videos
    route_prefix:          video
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
            title: {label: 'Заголовок'}
            content: {label: 'Ссылка на видео'}
            meta_description: {label: 'Мета описание'}
            meta_keywords: {label: 'Ключевые слова'}
            created_at: {label: 'Дата создания'}
            updated_at: {label: 'Дата редактирования'}
      list:    
            title: Видеозаписи
            layout:  tabular
            display: [title, created_at, updated_at]
            max_per_page: 10
            batch_actions: {}
            object_actions:
                _edit: {label: 'Редактировать'}
                _delete: {label: 'Удалить'}
      filter: 
            class: false
      form:    ~
      edit:    
            title: Редактирование видеозаписи "%%Title%%"
      new:
            title: Добавление видеозаписи
            actions:
                _list: ~
                _save: ~